### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prestonvanloon**
Hi @gampleman,

I'd like to be recognized as an author of this library. Since I had written it [originally](https://github.com/prestonvanloon/angulartics-newrelic-insights).

Thanks,
Preston

### CODE REVIEW

**Comment by gampleman** [comment]
I believe you are mistaken, as this was originally written by myself, as can be seen in this PR: https://github.com/angulartics/angulartics/pull/370

**Comment by prestonvanloon** [comment]
Sorry about that. It was some time ago.

**Comment by prestonvanloon** [comment]
Can you email me (preston@machinepowered.com) about transferring the npm repository? This is where my confusion stemmed from since it is still listed under my name.

**Comment by gampleman** [comment]
Ah so I think I understand what happened.

1. [I wrote the source code for the plugin itself in June 2015 and submitted it to the then monolithic angulartics repo](https://github.com/angulartics/angulartics/pull/370).
2. [That repo was to be broken up in July 2015 and I volunteered myself as  maintainer](https://github.com/angulartics/angulartics/issues/390). However I didn't actually do anything (for various reasons).
3. You probably then did the migration to this repository of the original source code adding things like a `package.json` and a `travis.yaml` to make it stand on its own two feet (although github seems to think [I did that](https://github.com/angulartics/angulartics-newrelic-insights/commit/b43f4203762c9b5b6b2e573b47df23a65ac296dd), although I have no memory of doing that). This explains why the npm thing is in your name.

Given the fair amount of work that must have took, I'm happy to acknowledge you as a contributor on the readme (or alternatively delete myself and have the GitHub [Contributors](https://github.com/angulartics/angulartics-newrelic-insights/graphs/contributors) page speak for itself). If you'd rather transfer the repo to my npm account, that's fine too.

**Pull request closed without merging**
